//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 07:37:17 AM OEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exlp.sourceforge.net/dirsize", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sf.exlp.addon.dirsize.data.jaxb;
